version: '3'
services:
  some-mongo:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mysecretpassword
    volumes:
      - db-data:/data/db
  some-mongo-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=some-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mysecretpassword
    depends_on:
      - some-mongo
  springmongoapp:
    image: springmongoapp:6.0
    ports:
      - 8090:8090
      - 5005:5005
    depends_on:
      - some-mongo
volumes:
  db-data: