apiVersion: v1
kind: Service
metadata:
  name: springmongoapp-service
  namespace: default
  labels:
    app: springmongoapp-service
spec:
  ports:
    -
      port: 8090
      targetPort: 8090
      protocol: TCP
      nodePort: 30000
  selector:
    app: springmongodep
  type: NodePort


