apiVersion: apps/v1
kind: Deployment
metadata:
  name: springmongodep
  namespace: default
  labels:
    app: springmongodep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springmongodep
  template:
    metadata:
      labels:
        app: springmongodep
    spec:
      containers:
        -
          image: shashi72174/springmongoapp
          imagePullPolicy: Always
          ports:
            -
              containerPort: 8090
              name: springmongodep
          name: springmongodep