apiVersion: apps/v1
kind: Deployment
metadata:
  name: springmongoapp-deploy
  namespace: default
  labels:
    app: springmongoappdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springmongoappdeploy
  template:
    metadata:
      labels:
        app: springmongoappdeploy
    spec:
      containers:
        -
          image: shashi72174/springmongoapp
          imagePullPolicy: Always
          ports:
            -
              containerPort: 8090
              name: springmongoappdeploy
          name: springmongoappdeploy