server:
  port: 8090


spring:
  data:
    mongodb:
      authentication-database: admin
      database: employeeDB
      host: some-mongo
      port: 27017
      username: root
      password: mysecretpassword